### ISSUE TITLE
Sur l'Open review

### ISSUE THREAD

**Issue by KrullTheWarriorKing** [Open-Models/Brique#289]
Pour présenter pourquoi l'open source est intéressant, cet article présente pourquoi est-ce que le peer-reviewed est une expérimentation historiquement récente qui n'a pas marché. 

https://experimentalhistory.substack.com/p/the-rise-and-fall-of-peer-review 

Merci pour le boulot en tout cas.

**Comment by AbcSxyZ** [comment]
Est-ce que le peer review est un échec, ou est-ce que ça qu'il y a des problèmes et des améliorations à faire ? Je n'ai pas la prétention de trancher, ce que je trouve important c'est de comprendre qu'on ne sait pas encore vraiment faire la science.

Si le peer review est une grande expérience, on est quand même un peu tous continuellement des cobayes de l'Histoire 🙃

En tout cas c'est un gros sujet, le cas des communs numériques est aussi intéressant pour se questionner sur ce processus, vu qu'on s'appuie sur qqch dont les gens ont besoins, vont co-produire, vont dépendre, et pas seulement lire le papier d'un autre parce qu'il a besoin d'être validé.

Il y a clairement des limites, mais il semble quand même se passer des choses quand tu as des gens experts qui collaborent, tu as la "loi de linus" (hypothèse fausse d'Eric Raymond, cathdral and the bazaar) qui dit "given enough eyeballs, all bugs are shallow", une forme d'intelligence collective qui va tendre à améliorer le logiciels. Tu as des phénomène similaire sur Wikipédia, avec les pages beaucoup revues qui tendraient à une meilleure qualité. Étant un des sites les plus visités au monde, certains articles deviennent les ressources les plus revues au monde : https://theconversation.com/students-are-told-not-to-use-wikipedia-for-research-but-its-a-trustworthy-source-168834

Des configurations qui sont vraiment différentes pour essayer de comprendre les impacts de l'évaluation par les pairs.

L'article soulève tout un ensemble de problèmes réel, mais peut-être que l'évaluation par les pairs n'est pas le maux de tous les problèmes et que ses imperfections ne sont pas forcément le signe de son inutilité. Comme le déclin de la recherche donné dans l'article, dans quelle mesure c'est par exemple aussi dû au contexte socio-économique, une logique libérale avec une baisse de la recherche d'intérêt publique vers une recherche plus orientée à des fins économiques.

Plein de choses à dire sur plein de points, comment l'orientation mercantile du marché de l'édition scientifique, ou le manque de formations des chercheurs à l'évaluation par les pairs où ils vont souvent être laissé à eux-mêmes et les quelques personnes de leur entourage.

Presque (ou déjà) des problèmes de société, comme la crise de la reproductibilité, mais le mouvement de l'open science interroge plein de points cités (faire des rapport d'évaluations publiques, délai réduit/supprimé avec pré-publication). En tout ça évolue, tu as notamment la [Coalition for Advancing Research Assessment](https://coara.eu/) (et pleins d'autres acteurs) qui tentent de faire évoluer ces différents aspects.

Quelle que soit la solution à cette situation, je crois qu'elle sera forcément expérimentale 😅 Des évolutions importantes à suivre !

J'avais vu passer l'article, mais je ne l'avais pas ajouté à l'occasion, toujours bien d'avoir des articles qui viennent questionner les bénéfices (voir l'utilité !) de l'évaluation par les pairs, ajout aux ressources en cours : https://github.com/Open-Models/Brique/pull/291
